      
import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatToolbarModule,
  MatFormFieldModule,
  MatTableModule,
  MatCardModule,
  MatInputModule,
  MatCheckboxModule,
  MatSelectModule,
  MatIconModule,
  MatDialogModule,
  MatListModule,
  MatChipsModule,
  MatAutocompleteModule,
  MatTooltipModule,
  MatPaginatorModule,
  MatSortModule,
  MatSidenavModule,
  MatRadioModule,
  MatTreeModule,
} from '@angular/material';
import {MatProgressSpinnerModule} from '@angular/material/progress-spinner';
import {MatExpansionModule} from '@angular/material/expansion';

@NgModule({
    imports: [
      MatButtonModule,
      MatToolbarModule,
      MatFormFieldModule,
      MatTableModule,
      MatCardModule,
      MatInputModule,
      MatCheckboxModule,
      MatSelectModule,
      MatFormFieldModule,
      MatIconModule,
      MatDialogModule,
      MatListModule,
      MatChipsModule,
      MatAutocompleteModule,
      MatTooltipModule,
      MatPaginatorModule,
      MatSortModule,
      MatSidenavModule,
      MatRadioModule,
      MatTreeModule,
      MatProgressSpinnerModule,
      MatExpansionModule,
      ],
    exports: [
      MatButtonModule,
      MatToolbarModule,
      MatFormFieldModule,
      MatTableModule,
      MatCardModule,
      MatInputModule,
      MatCheckboxModule,
      MatSelectModule,
      MatFormFieldModule,
      MatIconModule,
      MatDialogModule,
      MatListModule,
      MatChipsModule,
      MatAutocompleteModule,
      MatTooltipModule,
      MatPaginatorModule,
      MatSortModule,
      MatSidenavModule,
      MatRadioModule,
      MatTreeModule,
      MatProgressSpinnerModule,
      MatExpansionModule,
    ]
})
export class MaterialModule {}
